# Generated by Django 3.2 on 2021-04-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210410_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='nationality',
            field=models.CharField(choices=[('US', 'American'), ('EN', 'English'), ('CH', 'Chinese'), ('FR', 'French'), ('DE', 'German'), ('IT', 'Italian'), ('JP', 'Japanese'), ('CH', 'Swiss'), ('TW', 'Taiwanese'), ('PL', 'Polish')], max_length=64),
        ),
    ]
