# Generated by Django 3.1.8 on 2021-04-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20210410_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='ink',
            name='used_up_when',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ink',
            name='used_up',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
