# Generated by Django 3.1.8 on 2021-04-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20210410_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='ink',
            name='line',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
