# Generated by Django 3.1.8 on 2021-04-10 23:21

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_ink_line'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FillingSystem',
        ),
        migrations.AlterField(
            model_name='pen',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='PLN', max_digits=7),
        ),
    ]
