# Generated by Django 3.1.8 on 2021-04-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20210410_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='penrotation',
            name='in_use',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='penrotation',
            name='whos',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
