# Generated by Django 3.1.8 on 2021-04-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20210411_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penrotation',
            name='in_use',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='penrotation',
            name='whos',
            field=models.CharField(default='Tomek', max_length=64),
            preserve_default=False,
        ),
    ]
