# Generated by Django 3.2 on 2021-04-10 17:50

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20201029_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='pen',
            name='klass',
        ),
        migrations.RemoveField(
            model_name='pen',
            name='rot',
        ),
        migrations.AddField(
            model_name='pen',
            name='age',
            field=models.CharField(choices=[('Modern', 'Modern'), ('Vintage', 'Vintage')], default='modern', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pen',
            name='rotation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='items.penrotation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penrotation',
            name='how_often',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='brand',
            name='nationality',
            field=models.CharField(choices=[('US', 'American'), ('CH', 'Chinese'), ('FR', 'French'), ('DE', 'German'), ('IT', 'Italian'), ('JP', 'Japanese'), ('CH', 'Swiss'), ('TW', 'Taiwanese')], max_length=64),
        ),
        migrations.AlterField(
            model_name='ink',
            name='bought',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ink',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.brand'),
        ),
        migrations.AlterField(
            model_name='ink',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Blue Black', 'Blue Black'), ('Brown', 'Brown'), ('Burgundy', 'Burgundy'), ('Green', 'Green'), ('Grey', 'Grey'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Red', 'Red'), ('Royal Blue', 'Royal Blue'), ('Teal', 'Teal'), ('Turquoise', 'Turquoise'), ('Yellow', 'Yellow')], max_length=64),
        ),
        migrations.AlterField(
            model_name='ink',
            name='how',
            field=models.CharField(choices=[('Bought', 'Bought'), ('Present', 'Present')], max_length=64),
        ),
        migrations.AlterField(
            model_name='ink',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='ink',
            name='obtained_from',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='ink',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='PLN', max_digits=5),
        ),
        migrations.AlterField(
            model_name='ink',
            name='used_up',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='ink',
            name='volume',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nib',
            name='cut',
            field=models.CharField(choices=[('round', 'round'), ('stub', 'stub'), ('italic', 'italic'), ('SIG', 'SIG'), ('WA', 'WA'), ('flex', 'flex'), ('architect', 'architect')], max_length=64),
        ),
        migrations.AlterField(
            model_name='nib',
            name='material',
            field=models.CharField(choices=[('14k Gold', '14k Gold'), ('18k Gold', '18k Gold'), ('21k Gold', '21k Gold'), ('23k Palladium', '23k Palladium'), ('Steel', 'Steel')], max_length=64),
        ),
        migrations.AlterField(
            model_name='nib',
            name='width',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pen',
            name='bought',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pen',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.brand'),
        ),
        migrations.AlterField(
            model_name='pen',
            name='filling',
            field=models.CharField(choices=[('Bulkfiller', 'Bulkfiller'), ('Eyedropper', 'Eyedropper'), ('Lever', 'Lever'), ('Piston', 'Piston'), ('Plunger', 'Plunger'), ('Shutoff valve', 'Shutoff valve'), ('Squeeze', 'Squeeze'), ('c/c', 'c/c')], max_length=64),
        ),
        migrations.AlterField(
            model_name='pen',
            name='model',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pen',
            name='obtained_from',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pen',
            name='out',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='pen',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='PLN', max_digits=5),
        ),
        migrations.AlterField(
            model_name='penrotation',
            name='priority',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usage',
            name='begin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usage',
            name='ink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.ink'),
        ),
        migrations.AlterField(
            model_name='usage',
            name='nib',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.nib'),
        ),
        migrations.AlterField(
            model_name='usage',
            name='pen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.pen'),
        ),
    ]
