# Generated by Django 3.1.8 on 2021-04-18 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_auto_20210411_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='ink',
            name='rotation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='items.penrotation'),
            preserve_default=False,
        ),
    ]
