# Generated by Django 3.1.8 on 2021-04-19 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_auto_20210418_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='pen',
            name='finish',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='usage',
            name='begin',
            field=models.DateField(default=datetime.date(2021, 4, 19)),
        ),
    ]
