# Generated by Django 6.0.4 on 2026-04-21 06:29

import dpypen.items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_invitecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='penphoto',
            name='image_styled',
            field=models.ImageField(blank=True, null=True, upload_to=dpypen.items.models.pen_photo_path),
        ),
    ]
