# Generated by Django 6.0.4 on 2026-04-21 10:32

import django.db.models.deletion
import dpypen.items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_penphoto_image_styled'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=dpypen.items.models.writing_sample_path)),
                ('image_clean', models.ImageField(blank=True, null=True, upload_to=dpypen.items.models.writing_sample_path)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='items.usage')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
