# Generated by Django 6.0.4 on 2026-04-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_rename_bought_to_obtained'),
    ]

    operations = [
        migrations.AddField(
            model_name='ink',
            name='moi_url',
            field=models.URLField(blank=True),
        ),
    ]
