# Generated by Django 6.0.4 on 2026-04-21 11:40

import django.db.models.deletion
import dpypen.items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_ink_moi_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='InkSwatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=dpypen.items.models.ink_swatch_path)),
                ('image_clean', models.ImageField(blank=True, null=True, upload_to=dpypen.items.models.ink_swatch_path)),
                ('position', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swatches', to='items.ink')),
            ],
            options={
                'ordering': ['position', '-uploaded_at'],
            },
        ),
    ]
