# Generated by Django 6.0.4 on 2026-08-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0024_ink_sampled_hex"),
    ]

    operations = [
        migrations.AddField(
            model_name="penphoto",
            name="kind",
            field=models.CharField(
                choices=[("main", "Uncapped"), ("nib", "Nib close-up"), ("capped", "Capped"), ("other", "Other")], default="other", max_length=8
            ),
        ),
        migrations.AddField(
            model_name="penphoto",
            name="source_note",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
