# Generated by Django 6.0.4 on 2026-08-28 06:35

import dpypen.items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0025_penphoto_kind_penphoto_source_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="penphoto",
            name="styled_thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to=dpypen.items.models.pen_photo_path),
        ),
    ]
